name: FNAmplifications
version: '${project.version}'
main: ne.fnfal113.fnamplifications.FNAmplifications
api-version: 1.16
authors: [ FN_FAL113 ]
description: Custom Addon that includes my other addons for slimefun
website: https://github.com/FN-FAL113
depend: 
  - Slimefun
  - GuizhanLibPlugin
softdepend:
  - LiteXpansion
  - SimpleMaterialGenerators
  - Vault
commands:
  fngear:
    description: 检查 FN Gears 进度的命令
    default: true
    usage: /<command>
permissions:
  fngear.levelupgears:
    description: 用于调平玩家磨损的FN齿轮
    default: op
