name: FNAmplifications
version: '${project.version}'
main: ne.fnfal113.fnamplifications.FNAmplifications
api-version: 1.17
authors: [ FN_FAL113 ]
description: Explore plethora of in-game items from machines, tools, pvp and many more!
website: https://github.com/FN-FAL113
depend: 
  - Slimefun
  - GuizhanLibPlugin
softdepend:
  - SimpleMaterialGenerators
  - Vault
commands:
  fngear:
    description: 用于检查玩家所穿戴的FN装备进度的命令
    default: true
    usage: /<command>
  fnshockwavetest:
    description: 用于测试来自Shockwave宝石的冲击波效果的命令
    default: op
    usage: /<command>
permissions:
  fngear.levelupgears:
    description: 用于调平玩家磨损的FN齿轮
    default: op
  fnshockwave.test:
    description: 用于测试冲击波宝石的冲击波效果
    default: op
